//
//  ListMoviesPresenter.swift
//  MovieApp
//
//  Created by Sami Youssef on 11/12/18.
//  Copyright (c) 2018 Sami Youssef. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesPresentationLogic {
    func displayMovieList(response: ListMovies.FetchMovieList.Response)
}

class ListMoviesPresenter: ListMoviesPresentationLogic {
    weak var viewController: ListMoviesDisplayLogic?

    // MARK: Do something
    func displayMovieList(response: ListMovies.FetchMovieList.Response) {
        let viewModel = ListMovies.FetchMovieList.ViewModel(movieLits: response.movieLits)
        viewController?.displayMovieList(viewModel: viewModel)
    }
}
