//
//  ListMoviesWorker.swift
//  MovieApp
//
//  Created by Sami Youssef on 11/12/18.
//  Copyright (c) 2018 Sami Youssef. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListMoviesWorker {

    func loadMovieList(completion: @escaping ([MovieObj]?)->Void) {
        let request = ListMovies.FetchMovieList.Request()
        let networkDispatcher = URLSessionNetworkDispatcher(session: URLSession.shared)
        request.excute(dispatcher: networkDispatcher, onSuccess: { (movieResponse: MovieResponse) in
            completion(movieResponse.results)
        }) { (error: Error) in
            completion(nil)
        }
    }

}
