//
//  ListMoviesInteractor.swift
//  MovieApp
//
//  Created by Sami Youssef on 11/12/18.
//  Copyright (c) 2018 Sami Youssef. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesBusinessLogic {
    func fetchMovieList(request: ListMovies.FetchMovieList.Request)
}

protocol ListMoviesDataStore {
    //var name: String { get set }
}

class ListMoviesInteractor: ListMoviesBusinessLogic, ListMoviesDataStore {
    var presenter: ListMoviesPresentationLogic?
    var worker: ListMoviesWorker?

    // MARK: Do something
    func fetchMovieList(request: ListMovies.FetchMovieList.Request) {
        worker = ListMoviesWorker()
        worker?.loadMovieList(completion: { (movieList) in
            let response = ListMovies.FetchMovieList.Response(movieLits: movieList ?? [MovieObj]())
            self.presenter?.displayMovieList(response: response)
        })
    }
}
